name: 🗑️ Execute Cleanup

on:
  workflow_dispatch:
    inputs:
      confirm_cleanup:
        description: 'Type DELETE to confirm'
        required: true
        type: string
        default: ''

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JFrog OIDC login
        # Temporary workaround: using forked action until upstream fix
        # uses: jfrog/setup-jfrog-cli@v4
        uses: EyalDelarea/setup-jfrog-cli@swampUpAppTrust

      - name: Configure JFrog URL
        run: |
          jf c add --interactive=false --url "${{ vars.JFROG_URL }}" --access-token ""

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Execute Cleanup
        env:
          JFROG_URL: ${{ vars.JFROG_URL }}
          JFROG_ADMIN_TOKEN: ${{ secrets.JFROG_ADMIN_TOKEN }}
          CONFIRM_CLEANUP: ${{ inputs.confirm_cleanup }}
        run: |
          python bookverse-demo-init/scripts/execute_cleanup.py \
            --project bookverse \
            --base-url "${JFROG_URL}" \
            --token "${JFROG_ADMIN_TOKEN}" \
            --confirm "${CONFIRM_CLEANUP}"


