# Evidence Matrix Configuration for BookVerse Demo
# This file defines which evidence types are required for each package type and stage

evidence_matrix:
  
  # Package-level evidence (attached during CI build to packages)
  package_evidence:
    
    docker:
      - name: "pytest-results"
        predicate_type: "https://pytest.org/evidence/results/v1"
        description: "Unit test results and coverage from pytest"
        required: true
        
      - name: "sast-scan"
        predicate_type: "https://checkmarx.com/evidence/sast/v1.1"
        description: "Static Application Security Testing results"
        required: true
    
    python:
      - name: "pytest-results"
        predicate_type: "https://pytest.org/evidence/results/v1"
        description: "Unit test results and coverage from pytest"
        required: true
    
    generic:
      - name: "config-bundle"
        predicate_type: "Artifact Bundle"
        description: "Configuration and resource bundle verification (tar.gz files)"
        required: true
        note: "For services that package config/ and resources/ directories as tar.gz files"

  # Build-level evidence (attached during CI build to build info)
  build_evidence:
    
    - name: "fossa-license-scan"
      predicate_type: "https://fossa.com/evidence/license-scan/v2.1"
      description: "License compliance scan results for all dependencies"
      required: true
      
    - name: "sonar-quality-gate"
      predicate_type: "https://sonarsource.com/evidence/quality-gate/v1"
      description: "Code quality analysis and quality gate results"
      required: true

  # Application version evidence (attached during promotion to release bundles)
  application_evidence:
    
    unassigned:  # CI build stage
      - name: "slsa-provenance"
        predicate_type: "https://slsa.dev/provenance/v1"
        description: "SLSA provenance for supply chain security"
        required: true
        attach_stage: "UNASSIGNED"
        gate_for_promotion_to: "DEV"
        
      - name: "jira-release"
        predicate_type: "https://atlassian.com/evidence/jira/release/v1"
        description: "Jira release notes and ticket tracking"
        required: true
        attach_stage: "UNASSIGNED"
        gate_for_promotion_to: "DEV"
    
    dev:  # DEV promotion stage
      - name: "smoke-tests"
        predicate_type: "https://bookverse.com/evidence/smoke-tests/v1"
        description: "Basic smoke tests in DEV environment"
        required: false  # Not yet implemented
        attach_stage: "DEV"
        gate_for_promotion_to: "QA"
    
    qa:  # QA promotion stage
      - name: "dast-scan"
        predicate_type: "https://invicti.com/evidence/dast/v3"
        description: "Dynamic Application Security Testing results"
        required: false  # Not yet implemented
        attach_stage: "QA"
        gate_for_promotion_to: "STAGING"
        
      - name: "api-tests"
        predicate_type: "https://postman.com/evidence/collection/v2.2"
        description: "API integration test results"
        required: false  # Not yet implemented
        attach_stage: "QA"
        gate_for_promotion_to: "STAGING"
    
    staging:  # STAGING promotion stage
      - name: "iac-scan"
        predicate_type: "https://snyk.io/evidence/iac/v1"
        description: "Infrastructure as Code security scan"
        required: true
        attach_stage: "STAGING"
        gate_for_promotion_to: "PROD"
        
      - name: "pentest"
        predicate_type: "https://cobalt.io/evidence/pentest/v1"
        description: "Penetration testing results"
        required: true
        attach_stage: "STAGING"
        gate_for_promotion_to: "PROD"
        
      - name: "change-approval"
        predicate_type: "https://servicenow.com/evidence/change-req/v1"
        description: "Change management approval"
        required: true
        attach_stage: "STAGING"
        gate_for_promotion_to: "PROD"
    
    prod:  # Production verification stage
      - name: "deployment-verification"
        predicate_type: "https://argoproj.github.io/argo-cd/evidence/deployment/v1"
        description: "Production deployment verification and health checks"
        required: false  # Not yet implemented
        attach_stage: "PROD"
        gate_for_promotion_to: null  # Final stage

# Service-specific overrides (optional)
service_overrides:
  bookverse-web:
    package_evidence:
      docker:
        - name: "lighthouse-audit"
          predicate_type: "https://lighthouse.dev/evidence/audit/v1"
          description: "Web performance and accessibility audit"
          required: false
  
  bookverse-helm:
    package_evidence:
      generic:
        - name: "helm-lint"
          predicate_type: "https://helm.sh/evidence/lint/v1"
          description: "Helm chart linting results"
          required: true

# Demo configuration
demo_settings:
  randomization:
    enabled: true
    seed_source: "github_run_number"  # Use GitHub run number for consistent randomization
  
  template_variables:
    # Common variables available in all templates
    timestamp: "{{ NOW_TS }}"
    service_name: "{{ SERVICE_NAME }}"
    version: "{{ APP_VERSION }}"
    build_number: "{{ BUILD_NUMBER }}"
    commit_sha: "{{ GITHUB_SHA }}"
    actor: "{{ GITHUB_ACTOR }}"