name: 'Cleanup JFrog Platform for BookVerse Demo'
on:
  workflow_dispatch:
    inputs:
      confirm_cleanup:
        description: 'Type "DELETE" to confirm cleanup (this action cannot be undone)'
        required: true
        type: string
      skip_protection:
        description: 'Skip protection layer (NOT RECOMMENDED)'
        required: false
        default: false
        type: boolean

jobs:
  cleanup-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest

      - name: Configure JFrog CLI for Admin
        run: |
          jfrog config add bookverse-admin --url=${{ vars.JFROG_URL }} --access-token=${{ secrets.JFROG_ADMIN_TOKEN }} --interactive=false
          jfrog config use bookverse-admin

      - name: Validate Confirmation
        run: |
          echo "🔍 Validating confirmation input..."
          
          if [[ "${{ github.event.inputs.confirm_cleanup }}" != "DELETE" ]]; then
            echo "❌ Cleanup cancelled: Invalid confirmation input"
            echo "   You must type 'DELETE' to confirm cleanup"
            echo "   Current input: '${{ github.event.inputs.confirm_cleanup }}'"
            exit 1
          fi
          
          echo "✅ Cleanup confirmed. Proceeding with BookVerse project cleanup..."
          
          if [[ "${{ github.event.inputs.skip_protection }}" == "true" ]]; then
            echo "🚨 WARNING: Protection layer will be bypassed"
          else
            echo "🛡️ Protection layer active - will fail if interactive approval needed"
            echo "💡 Consider using Discovery workflow first for safer operation"
          fi

      - name: Cleanup BookVerse Project (PROJECT-BASED) with Safety Layer
        env:
          JFROG_URL: ${{ vars.JFROG_URL }}
          JFROG_ADMIN_TOKEN: ${{ secrets.JFROG_ADMIN_TOKEN }}
          VERBOSITY: 1
          SKIP_PROTECTION: ${{ github.event.inputs.skip_protection }}
        run: ./.github/scripts/setup/cleanup_project_based.sh

      - name: 📋 Cleanup Execution Summary
        if: always()
        run: |
          echo "## 🗑️ Cleanup Execution Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [[ "${{ job.status }}" == "success" ]]; then
            echo "✅ **Cleanup completed successfully**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "🎯 **All BookVerse project resources have been deleted**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 📋 What was deleted:" >> $GITHUB_STEP_SUMMARY
            echo "- 🚀 **Applications**: All project applications removed" >> $GITHUB_STEP_SUMMARY
            echo "- 📦 **Repositories**: All project repositories deleted" >> $GITHUB_STEP_SUMMARY
            echo "- 👥 **Users**: Project users/admins removed" >> $GITHUB_STEP_SUMMARY
            echo "- 🏷️ **Stages**: Project-level stages deleted" >> $GITHUB_STEP_SUMMARY
            echo "- 🔄 **Lifecycle**: Project lifecycle configuration cleared" >> $GITHUB_STEP_SUMMARY
            echo "- 🎯 **Project**: BookVerse project completely removed" >> $GITHUB_STEP_SUMMARY
          elif [[ "${{ github.event.inputs.skip_protection }}" != "true" ]]; then
            echo "❌ **Cleanup failed - Protection layer active**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "🛡️ **The protection layer blocked execution**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 💡 To proceed with deletion:" >> $GITHUB_STEP_SUMMARY
            echo "1. 🔍 **Run Discovery workflow first** to see what will be deleted" >> $GITHUB_STEP_SUMMARY
            echo "2. 🗑️ **Re-run this workflow** with skip_protection=true" >> $GITHUB_STEP_SUMMARY
            echo "3. ⚠️ **Type 'DELETE' to confirm** the destructive operation" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Cleanup execution failed**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "🔍 **Check the logs above for error details**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 💡 Common causes:" >> $GITHUB_STEP_SUMMARY
            echo "- 🔐 **Authentication issues** with JFrog platform" >> $GITHUB_STEP_SUMMARY
            echo "- 🔒 **Resources locked** by other processes" >> $GITHUB_STEP_SUMMARY
            echo "- 🌐 **Network connectivity** problems" >> $GITHUB_STEP_SUMMARY
            echo "- ⚠️ **Resource dependencies** preventing deletion" >> $GITHUB_STEP_SUMMARY
          fi
      
      # Note: This will completely remove the BookVerse project and all resources!
      # Use with caution - this action cannot be undone.
