name: 'Initialize JFrog Platform for BookVerse Demo (Optimized)'

on:
  workflow_dispatch:

env:
  # Centralized environment variables - reduces 30+ lines of repetition
  JFROG_URL: ${{ vars.JFROG_URL }}
  JFROG_ADMIN_TOKEN: ${{ secrets.JFROG_ADMIN_TOKEN }}

jobs:
  setup-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest

      - name: Initialize JFrog Platform
        run: |
          # Configure JFrog CLI for admin access
          jfrog config add bookverse-admin --url="$JFROG_URL" --access-token="$JFROG_ADMIN_TOKEN" --interactive=false
          jfrog config use bookverse-admin
          
          # Validate environment and connectivity
          ./.github/scripts/setup/validate_environment.sh

      - name: Create Core Infrastructure
        run: |
          # Execute core setup scripts in optimal order
          ./.github/scripts/setup/create_project.sh
          ./.github/scripts/setup/create_stages.sh
          ./.github/scripts/setup/create_repositories.sh

      - name: Setup Users and Applications
        run: |
          # Execute user and application setup
          ./.github/scripts/setup/create_users.sh
          ./.github/scripts/setup/create_applications.sh

      - name: Configure Security Integration
        run: |
          # Configure OIDC integrations for GitHub Actions
          ./.github/scripts/setup/create_oidc.sh

      - name: Validate Complete Setup
        run: |
          # Final validation of all created resources
          ./.github/scripts/setup/validate_setup.sh
