name: 🔍 Investigate Actual Project Resources

on:
  workflow_dispatch:
    inputs:
      deep_investigation:
        description: 'Run deep investigation of all resources'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  PROJECT_KEY: bookverse

jobs:
  investigate-resources:
    runs-on: ubuntu-latest
    name: Investigate Project Resources
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest
          
      - name: Configure JFrog CLI for Admin
        run: |
          jf config add bookverse-admin \
            --url="${{ secrets.JFROG_URL }}" \
            --access-token="${{ secrets.JFROG_ADMIN_TOKEN }}" \
            --interactive=false
          jf config use bookverse-admin
          echo "✅ JFrog CLI configured successfully"
          
      - name: Investigate Actual Resources
        env:
          JFROG_URL: ${{ secrets.JFROG_URL }}
          JFROG_ADMIN_TOKEN: ${{ secrets.JFROG_ADMIN_TOKEN }}
        run: |
          echo "🔍 RUNNING COMPREHENSIVE RESOURCE INVESTIGATION"
          echo "==============================================="
          echo "User reported: builds, artifacts, repositories still exist"
          echo "Script reported: 0 resources found"
          echo "GOAL: Find what our discovery logic is missing"
          echo ""
          
          ./.github/scripts/setup/investigate_actual_resources.sh
          
      - name: Upload Investigation Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: resource-investigation-results
          path: /tmp/resource_investigation_*
          retention-days: 7
