name: 🔄 Switch JFrog Platform Deployment (JPD)

on:
  workflow_dispatch:
    inputs:
      jpd_host:
        description: 'JFrog Platform Host (e.g., https://mycompany.jfrog.io)'
        required: true
        type: string
      admin_token:
        description: 'JFrog Admin Token for the new platform'
        required: true
        type: string
      confirm_switch:
        description: 'Type "SWITCH" to confirm platform migration'
        required: true
        type: string

env:
  # GitHub token for updating other repositories
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  switch-jpd-platform:
    runs-on: ubuntu-latest
    name: Switch JPD Platform
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest
          
      - name: Validate Confirmation
        run: |
          if [[ "${{ github.event.inputs.confirm_switch }}" != "SWITCH" ]]; then
            echo "❌ Platform switch cancelled: Invalid confirmation input"
            echo "   You must type 'SWITCH' to confirm platform migration"
            exit 1
          fi
          echo "✅ Platform switch confirmed. Proceeding with JPD migration..."
          
      - name: Switch JFrog Platform
        env:
          NEW_JFROG_URL: ${{ github.event.inputs.jpd_host }}
          NEW_JFROG_ADMIN_TOKEN: ${{ github.event.inputs.admin_token }}
        run: |
          echo "🔄 Starting JFrog Platform Deployment (JPD) Switch"
          echo "=================================================="
          echo "From: ${{ vars.JFROG_URL || 'https://evidencetrial.jfrog.io' }}"
          echo "To: ${{ github.event.inputs.jpd_host }}"
          echo ""
          
          ./.github/scripts/setup/switch_jpd_platform.sh
          
      - name: Validate New Platform
        env:
          NEW_JFROG_URL: ${{ github.event.inputs.jpd_host }}
          NEW_JFROG_ADMIN_TOKEN: ${{ github.event.inputs.admin_token }}
        run: |
          echo "🔍 Validating new platform connectivity..."
          
          # Test the new platform is accessible
          if curl -s --fail --header "Authorization: Bearer $NEW_JFROG_ADMIN_TOKEN" \
              "${NEW_JFROG_URL}/artifactory/api/system/ping" > /dev/null; then
            echo "✅ New platform validation successful"
          else
            echo "❌ New platform validation failed"
            exit 1
          fi
          
          echo ""
          echo "🎯 JPD Platform Switch Summary:"
          echo "================================"
          echo "✅ Host validation: Passed"
          echo "✅ Connectivity test: Passed" 
          echo "✅ Service availability: Verified"
          echo "✅ All repositories updated: Confirmed"
          echo ""
          echo "🚀 BookVerse is now configured for the new JPD platform!"
