name: '🔍 Discover Cleanup'

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/🔍-discover-cleanup.yml'
      - '.github/scripts/setup/cleanup_project_based.sh'

permissions:
  contents: write

jobs:
  discover:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest

      - name: Configure JFrog CLI for Admin
        env:
          JFROG_URL: ${{ vars.JFROG_URL }}
          JFROG_ADMIN_TOKEN: ${{ secrets.JFROG_ADMIN_TOKEN }}
        run: |
          jfrog config add bookverse-admin --url="$JFROG_URL" --access-token="$JFROG_ADMIN_TOKEN" --interactive=false --overwrite
          jfrog config use bookverse-admin

      - name: Run discovery-only (no deletion)
        env:
          JFROG_URL: ${{ vars.JFROG_URL }}
          JFROG_ADMIN_TOKEN: ${{ secrets.JFROG_ADMIN_TOKEN }}
          PROJECT_KEY: 'bookverse'
        run: |
          set -e
          cd .github/scripts/setup
          awk '/# PHASE 2:/{exit} {print}' cleanup_project_based.sh > discovery_only.sh
          chmod +x discovery_only.sh
          bash ./discovery_only.sh || true
          cd -

      - name: Commit shared discovery report
        run: |
          # Locate report anywhere in the workspace
          report_path=$(find "$GITHUB_WORKSPACE" -type f -name "*cleanup-report.json" -print -quit)
          if [[ -n "$report_path" ]]; then
            echo "Found report at: $report_path"
            mkdir -p .github
            cp "$report_path" .github/cleanup-report.json
            git config --global user.name "BookVerse Discovery Bot"
            git config --global user.email "discovery@bookverse.demo"
            git add .github/cleanup-report.json
            if git diff --cached --quiet; then
              echo "📋 No changes to commit for cleanup report"
            else
              git commit -m "chore: Update cleanup discovery report"
              git push origin ${{ github.ref_name }}
              echo "📋 Cleanup report committed and pushed"
            fi
          else
            echo "⚠️ No cleanup report found"
          fi

      - name: 📋 Discovery Report Summary
        run: |
          echo "## 🔍 Cleanup Discovery Report" >> $GITHUB_STEP_SUMMARY
          if [[ -f ".github/cleanup-report.json" ]]; then
            ts=$(jq -r '.metadata.timestamp' .github/cleanup-report.json)
            total=$(jq -r '.metadata.total_items' .github/cleanup-report.json)
            repos=$(jq -r '.metadata.discovery_counts.repositories' .github/cleanup-report.json)
            users=$(jq -r '.metadata.discovery_counts.users' .github/cleanup-report.json)
            apps=$(jq -r '.metadata.discovery_counts.applications' .github/cleanup-report.json)
            stages=$(jq -r '.metadata.discovery_counts.stages' .github/cleanup-report.json)
            builds=$(jq -r '.metadata.discovery_counts.builds' .github/cleanup-report.json)
            echo "Generated: $ts" >> $GITHUB_STEP_SUMMARY
            echo "Total items: $total" >> $GITHUB_STEP_SUMMARY
            echo "- 📦 Repositories: $repos" >> $GITHUB_STEP_SUMMARY
            echo "- 👥 Users: $users" >> $GITHUB_STEP_SUMMARY
            echo "- 🚀 Applications: $apps" >> $GITHUB_STEP_SUMMARY
            echo "- 🏷️ Stages: $stages" >> $GITHUB_STEP_SUMMARY
            echo "- 🔧 Builds: $builds" >> $GITHUB_STEP_SUMMARY
          else
            echo "No report generated" >> $GITHUB_STEP_SUMMARY
          fi
