name: '🔍 Discover Cleanup'

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/🔍-discover-cleanup.yml'
      - '.github/scripts/setup/cleanup_project_based.sh'

permissions:
  contents: write
  actions: write

jobs:
  discover-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest

      - name: Configure JFrog CLI for Admin
        env:
          JFROG_URL: ${{ vars.JFROG_URL }}
          JFROG_ADMIN_TOKEN: ${{ secrets.JFROG_ADMIN_TOKEN }}
        run: |
          jf c add bookverse-admin --url="${JFROG_URL}" --access-token="${JFROG_ADMIN_TOKEN}" --interactive=false --overwrite
          jf c use bookverse-admin

      - name: 🔍 Discovery Phase - Find Resources to Delete
        env:
          JFROG_URL: ${{ vars.JFROG_URL }}
          JFROG_ADMIN_TOKEN: ${{ secrets.JFROG_ADMIN_TOKEN }}
          PROJECT_KEY: 'bookverse'
        run: |
          # Run discovery only (no deletion)
          cd .github/scripts/setup
          
          # Copy the main script and modify it for discovery-only
          cp cleanup_project_based.sh discovery_only.sh
          
          # Remove the deletion phase - only keep discovery
          sed -i '/# PHASE 2: EXECUTION/,$d' discovery_only.sh
          echo 'echo "🛡️ DISCOVERY COMPLETE - NO DELETION PERFORMED"' >> discovery_only.sh
          echo 'echo "=============================================="' >> discovery_only.sh
          echo 'echo ""' >> discovery_only.sh
          echo 'echo "📋 To execute the deletion:"' >> discovery_only.sh
          echo 'echo "  1. Review the preview above carefully"' >> discovery_only.sh
          echo 'echo "  2. Run 🗑️ Execute Cleanup workflow"' >> discovery_only.sh
          echo 'echo "  3. Set SKIP_PROTECTION=true for automated deletion"' >> discovery_only.sh
          echo 'echo ""' >> discovery_only.sh
          echo 'echo "💾 Preview saved to: $preview_file"' >> discovery_only.sh
          echo 'exit 0' >> discovery_only.sh
          
          # Run discovery from the correct directory
          bash ./discovery_only.sh
          cd - # Return to root directory
          
          # Commit the shared report file to repository
          if [[ -f ".github/cleanup-report.json" ]]; then
            git config --global user.name "BookVerse Discovery Bot"
            git config --global user.email "discovery@bookverse.demo"
            git add .github/cleanup-report.json
            if git diff --cached --quiet; then
              echo "📋 No changes to commit for cleanup report"
            else
              git commit -m "chore: Update cleanup discovery report

Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
Project: bookverse
Status: Ready for cleanup execution

This report contains the current state of BookVerse resources
and is used by the cleanup workflow for safe deletion."
              git push origin main
              echo "📋 Cleanup report committed and pushed to repository"
            fi
          else
            echo "⚠️ Warning: Cleanup report file not found"
          fi

      - name: 📋 Discovery Report Summary
        run: |
          echo "## 🔍 Cleanup Discovery Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Discovery completed successfully**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Add report details to job summary  
          echo "### 📋 Next Steps:" >> $GITHUB_STEP_SUMMARY
          echo "1. 👀 **Review the discovery report above** carefully" >> $GITHUB_STEP_SUMMARY
          echo "2. 🗑️ **Run Execute Cleanup workflow** to execute deletion" >> $GITHUB_STEP_SUMMARY
          echo "3. ⚠️ **Type 'DELETE' and optionally set skip_protection=true** for execution" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ⚠️ Important:" >> $GITHUB_STEP_SUMMARY
          echo "- **🔍 Discover Cleanup** workflow **DOES NOT DELETE** anything" >> $GITHUB_STEP_SUMMARY
          echo "- Resources are only **discovered and reported**" >> $GITHUB_STEP_SUMMARY
          echo "- Use **🗑️ Execute Cleanup** workflow for actual deletion" >> $GITHUB_STEP_SUMMARY
