name: '🔍 Discover Cleanup'

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/🔍-discover-cleanup.yml'
      - '.github/scripts/setup/cleanup_project_based.sh'

permissions:
  contents: write

jobs:
  discover:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest

      - name: Configure JFrog CLI for Admin
        env:
          JFROG_URL: ${{ vars.JFROG_URL }}
          JFROG_ADMIN_TOKEN: ${{ secrets.JFROG_ADMIN_TOKEN }}
        run: |
          jfrog config add bookverse-admin --url="$JFROG_URL" --access-token="$JFROG_ADMIN_TOKEN" --interactive=false --overwrite
          jfrog config use bookverse-admin

      - name: Run discovery-only (no deletion)
        env:
          JFROG_URL: ${{ vars.JFROG_URL }}
          JFROG_ADMIN_TOKEN: ${{ secrets.JFROG_ADMIN_TOKEN }}
          PROJECT_KEY: 'bookverse'
        run: |
          # Do not use 'set -e' here; discovery functions handle errors internally
          cd .github/scripts/setup
          export SKIP_PROTECTION=true
          # Extract functions + discovery preview, stopping before PHASE 2 section
          awk '1;/# PHASE 2: ACTUAL DELETION/{exit}' cleanup_project_based.sh > discovery_only.sh
          chmod +x discovery_only.sh
          bash ./discovery_only.sh || true
          cd -

      - name: Commit shared discovery report
        run: |
          # Locate report anywhere in the workspace
          report_path=$(find "$GITHUB_WORKSPACE" -type f -name "*cleanup-report.json" -print -quit)
          if [[ -n "$report_path" ]]; then
            echo "Found report at: $report_path"
            mkdir -p .github
            dest_path=".github/cleanup-report.json"
            # Copy only if paths differ
            if [[ "$report_path" != "$GITHUB_WORKSPACE/$dest_path" ]]; then
              cp "$report_path" "$dest_path"
            else
              echo "Report already at $dest_path"
            fi
            git config --global user.name "BookVerse Discovery Bot"
            git config --global user.email "discovery@bookverse.demo"
            git add "$dest_path"
            if git diff --cached --quiet; then
              echo "📋 No changes to commit for cleanup report"
            else
              git commit -m "chore: Update cleanup discovery report"
              git push origin ${{ github.ref_name }}
              echo "📋 Cleanup report committed and pushed"
            fi
          else
            echo "⚠️ No cleanup report found"
          fi

      - name: 📋 Discovery Report Summary
        run: |
          echo "## 🔍 Cleanup Discovery Report" >> $GITHUB_STEP_SUMMARY
          if [[ -f ".github/cleanup-report.json" ]]; then
            ts=$(jq -r '.metadata.timestamp' .github/cleanup-report.json)
            total=$(jq -r '.metadata.total_items' .github/cleanup-report.json)
            repos=$(jq -r '.metadata.discovery_counts.repositories' .github/cleanup-report.json)
            users=$(jq -r '.metadata.discovery_counts.users' .github/cleanup-report.json)
            apps=$(jq -r '.metadata.discovery_counts.applications' .github/cleanup-report.json)
            stages=$(jq -r '.metadata.discovery_counts.stages' .github/cleanup-report.json)
            builds=$(jq -r '.metadata.discovery_counts.builds' .github/cleanup-report.json)
            echo "Generated: $ts" >> $GITHUB_STEP_SUMMARY
            echo "Total items: $total" >> $GITHUB_STEP_SUMMARY
            echo "- 📦 Repositories: $repos" >> $GITHUB_STEP_SUMMARY
            echo "- 👥 Users: $users" >> $GITHUB_STEP_SUMMARY
            echo "- 🚀 Applications: $apps" >> $GITHUB_STEP_SUMMARY
            echo "- 🏷️ Stages: $stages" >> $GITHUB_STEP_SUMMARY
            echo "- 🔧 Builds: $builds" >> $GITHUB_STEP_SUMMARY

            # Extract deletion preview content from report
            preview_file="/tmp/deletion_preview.txt"
            jq -r '.deletion_plan' .github/cleanup-report.json > "$preview_file"

            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🔎 Detailed Items Discovered" >> $GITHUB_STEP_SUMMARY

            # Repositories
            repo_list=$(grep -E '^  ❌ Repository:' "$preview_file" | sed 's/^  ❌ Repository: //') || true
            echo "#### 📦 Repositories ($repos)" >> $GITHUB_STEP_SUMMARY
            if [[ -n "$repo_list" ]]; then
              echo "$repo_list" | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
            else
              echo "- None" >> $GITHUB_STEP_SUMMARY
            fi

            # Users
            user_list=$(grep -E '^  ❌ User:' "$preview_file" | sed 's/^  ❌ User: //') || true
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "#### 👥 Users ($users)" >> $GITHUB_STEP_SUMMARY
            if [[ -n "$user_list" ]]; then
              echo "$user_list" | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
            else
              echo "- None" >> $GITHUB_STEP_SUMMARY
            fi

            # Applications
            app_list=$(grep -E '^  ❌ Application:' "$preview_file" | sed 's/^  ❌ Application: //') || true
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "#### 🚀 Applications ($apps)" >> $GITHUB_STEP_SUMMARY
            if [[ -n "$app_list" ]]; then
              echo "$app_list" | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
            else
              echo "- None" >> $GITHUB_STEP_SUMMARY
            fi

            # Stages
            stage_list=$(grep -E '^  ❌ Stage:' "$preview_file" | sed 's/^  ❌ Stage: //') || true
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "#### 🏷️ Stages ($stages)" >> $GITHUB_STEP_SUMMARY
            if [[ -n "$stage_list" ]]; then
              echo "$stage_list" | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
            else
              echo "- None" >> $GITHUB_STEP_SUMMARY
            fi

            # Builds
            build_list=$(grep -E '^  ❌ Build:' "$preview_file" | sed 's/^  ❌ Build: //') || true
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "#### 🔧 Builds ($builds)" >> $GITHUB_STEP_SUMMARY
            if [[ -n "$build_list" ]]; then
              echo "$build_list" | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
            else
              echo "- None" >> $GITHUB_STEP_SUMMARY
            fi

            echo "" >> $GITHUB_STEP_SUMMARY
            echo "<details>" >> $GITHUB_STEP_SUMMARY
            echo "<summary>📄 Raw Discovery Preview</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat "$preview_file" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY

            # Link to committed report in repository
            report_url="https://github.com/${GITHUB_REPOSITORY}/blob/${GITHUB_REF_NAME}/.github/cleanup-report.json"
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🔗 Report File" >> $GITHUB_STEP_SUMMARY
            echo "[View cleanup-report.json]($report_url)" >> $GITHUB_STEP_SUMMARY
          else
            echo "No report generated" >> $GITHUB_STEP_SUMMARY
          fi
