name: '🚀 Setup Platform'

on:
  workflow_dispatch:
    inputs:
      DEMO_MODE:
        description: 'Enable demo mode (verbose logs, request tracing)'
        required: false
        default: 'false'
        type: choice
        options: ['false', 'true']

env:
  # Centralized environment variables - reduces 30+ lines of repetition
  JFROG_URL: ${{ vars.JFROG_URL }}
  JFROG_ADMIN_TOKEN: ${{ secrets.JFROG_ADMIN_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  setup-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply DEMO_MODE settings
        if: ${{ inputs.DEMO_MODE == 'true' || env.DEMO_MODE == 'true' }}
        run: |
          echo "🔔 DEMO_MODE enabled"
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
          echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
          echo "HTTP_DEBUG_LEVEL=verbose" >> $GITHUB_ENV
          echo "BASH_XTRACE_ENABLED=1" >> $GITHUB_ENV

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest

      - name: Initialize JFrog Platform
        run: |
          # Configure JFrog CLI for admin access
          jf c add bookverse-admin --url "$JFROG_URL" --access-token "$JFROG_ADMIN_TOKEN" --interactive=false
          jf c use bookverse-admin
          jf c show
          
          # Validate environment and connectivity
          ./.github/scripts/setup/validate_environment.sh

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create Project
        run: |
          ./.github/scripts/setup/create_project.sh

      - name: Create Lifecycle Stages
        run: |
          ./.github/scripts/setup/create_stages.sh

      - name: Create Service Repositories
        run: |
          ./.github/scripts/setup/create_repositories.sh

      - name: Create Dependency Repositories
        run: |
          ./.github/scripts/setup/create_dependency_repos.sh

      - name: Pre-populate Dependencies Cache
        run: |
          ./.github/scripts/setup/prepopulate_dependencies.sh

      - name: Create Users
        run: |
          ./.github/scripts/setup/create_users.sh

      - name: Create Applications
        run: |
          ./.github/scripts/setup/create_applications.sh

      - name: Configure Security Integration
        run: |
          # Configure OIDC integrations for GitHub Actions
          ./.github/scripts/setup/create_oidc.sh

      - name: Setup Evidence Keys
        run: |
          # Generate keys (if not provided), upload trusted key to JFrog, and
          # distribute secrets/variables to service repos
          bash ./.github/scripts/setup/evidence_keys_setup.sh

      - name: Validate Complete Setup
        run: |
          # Final validation of all created resources
          ./.github/scripts/setup/validate_setup.sh

      - name: 📋 Setup Platform Summary
        if: always()
        run: |
          echo "## 🚀 Setup Platform Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [[ "${{ job.status }}" == "success" ]]; then
            echo "✅ **Platform setup completed successfully**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "🎯 **BookVerse demo environment is ready**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 📋 What was created:" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            # Get actual created resources details
            echo "#### 🎯 **Project & Configuration**" >> $GITHUB_STEP_SUMMARY
            echo "- **Project**: \`bookverse\` with full configuration" >> $GITHUB_STEP_SUMMARY
            echo "- **Lifecycle stages**: \`bookverse-DEV\`, \`bookverse-QA\`, \`bookverse-STAGING\` (+ system PROD)" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            echo "#### 📦 **Repositories Created**" >> $GITHUB_STEP_SUMMARY
            # Load project key for dynamic listing
            source ./.github/scripts/setup/config.sh
            project_key="${PROJECT_KEY:-bookverse}"
            # Fetch all repositories and filter by project prefix
            repos_json=$(curl -s -H "Authorization: Bearer ${JFROG_ADMIN_TOKEN}" "${JFROG_URL}/artifactory/api/repositories")
            repo_keys=$(echo "$repos_json" | jq -r --arg p "$project_key" '.[] | select(.key | startswith($p + "-")) | .key' 2>/dev/null || true)

            echo "**Service Repositories:**" >> $GITHUB_STEP_SUMMARY
            # New schema: <project>-<service>-<visibility>-<type>-<stage_group>-local
            service_list=$(echo "$repo_keys" | grep -E "^${project_key}-(inventory|recommendations|checkout|platform|web|helm)-(public|internal)-(python|docker|maven|npm|helm|generic)-(nonprod|release)-local$" || true)
            if [[ -n "$service_list" ]]; then echo "$service_list" | sed 's/^/- `&`/' >> $GITHUB_STEP_SUMMARY; else echo "- None" >> $GITHUB_STEP_SUMMARY; fi
            echo "" >> $GITHUB_STEP_SUMMARY

            echo "**Dependency Repositories:**" >> $GITHUB_STEP_SUMMARY
            dep_list=$(echo "$repo_keys" | grep -E "^${project_key}-(pypi|npm|dockerhub)-(remote|cache-local|virtual)$" || true)
            if [[ -n "$dep_list" ]]; then echo "$dep_list" | sed 's/^/- `&`/' >> $GITHUB_STEP_SUMMARY; else echo "- None" >> $GITHUB_STEP_SUMMARY; fi
            echo "" >> $GITHUB_STEP_SUMMARY

            
            echo "#### 👥 **Users Created**" >> $GITHUB_STEP_SUMMARY
            echo "**Management Users:**" >> $GITHUB_STEP_SUMMARY
            echo "- \`alice.developer@bookverse.com\` (Developer)" >> $GITHUB_STEP_SUMMARY
            echo "- \`bob.release@bookverse.com\` (Release Manager, Project Admin)" >> $GITHUB_STEP_SUMMARY
            echo "- \`charlie.devops@bookverse.com\` (DevOps Manager, Project Admin)" >> $GITHUB_STEP_SUMMARY
            echo "- \`diana.architect@bookverse.com\` (Platform Architect, Project Admin)" >> $GITHUB_STEP_SUMMARY
            echo "- \`edward.manager@bookverse.com\` (Engineering Manager, Project Admin)" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Service Owners:**" >> $GITHUB_STEP_SUMMARY
            echo "- \`frank.inventory@bookverse.com\` (Inventory Service)" >> $GITHUB_STEP_SUMMARY
            echo "- \`grace.ai@bookverse.com\` (Recommendations Service)" >> $GITHUB_STEP_SUMMARY
            echo "- \`henry.checkout@bookverse.com\` (Checkout Service)" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Pipeline Users:**" >> $GITHUB_STEP_SUMMARY
            echo "- \`pipeline.inventory@bookverse.com\`" >> $GITHUB_STEP_SUMMARY
            echo "- \`pipeline.recommendations@bookverse.com\`" >> $GITHUB_STEP_SUMMARY
            echo "- \`pipeline.checkout@bookverse.com\`" >> $GITHUB_STEP_SUMMARY
            echo "- \`pipeline.web@bookverse.com\`" >> $GITHUB_STEP_SUMMARY
            echo "- \`pipeline.platform@bookverse.com\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            echo "#### 🚀 **Applications** (AppTrust)" >> $GITHUB_STEP_SUMMARY
            echo "- \`bookverse-inventory\` → frank.inventory@bookverse.com [high criticality]" >> $GITHUB_STEP_SUMMARY
            echo "- \`bookverse-recommendations\` → grace.ai@bookverse.com [medium criticality]" >> $GITHUB_STEP_SUMMARY
            echo "- \`bookverse-checkout\` → henry.checkout@bookverse.com [high criticality]" >> $GITHUB_STEP_SUMMARY
            echo "- \`bookverse-platform\` → diana.architect@bookverse.com [high criticality]" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            echo "#### 🔐 **Security & Integration**" >> $GITHUB_STEP_SUMMARY
            echo "**OIDC Integrations:**" >> $GITHUB_STEP_SUMMARY
            echo "- \`${project_key}-inventory-github\` → frank.inventory@bookverse.com" >> $GITHUB_STEP_SUMMARY
            echo "- \`${project_key}-recommendations-github\` → grace.ai@bookverse.com" >> $GITHUB_STEP_SUMMARY
            echo "- \`${project_key}-checkout-github\` → pipeline.checkout@bookverse.com" >> $GITHUB_STEP_SUMMARY
            echo "- \`${project_key}-platform-github\` → diana.architect@bookverse.com" >> $GITHUB_STEP_SUMMARY
            echo "- \`${project_key}-web-github\` → pipeline.web@bookverse.com" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Evidence Keys:**" >> $GITHUB_STEP_SUMMARY
            echo "- Smart conflict resolution implemented" >> $GITHUB_STEP_SUMMARY
            echo "- Keys distributed to all service repositories" >> $GITHUB_STEP_SUMMARY
            echo "- Public key uploaded to JFrog Platform as trusted key" >> $GITHUB_STEP_SUMMARY
            # Resolve key alias using the script default/env rather than grepping logs
            key_alias=${EVIDENCE_KEY_ALIAS:-BookVerse-Evidence-Key}
            echo "- Key alias: \`$key_alias\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🎯 Next Steps:" >> $GITHUB_STEP_SUMMARY
            echo "1. 🏗️ **Run service CI/CD workflows** to build and deploy applications" >> $GITHUB_STEP_SUMMARY
            echo "2. 🧪 **Test the demo applications** using the provided endpoints" >> $GITHUB_STEP_SUMMARY
            echo "3. 🔍 **Explore JFrog Platform** to see created resources" >> $GITHUB_STEP_SUMMARY
            echo "4. 📖 **Check documentation** for detailed usage instructions" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Platform setup failed**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "🔍 **Check the logs above for error details**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 💡 Common causes:" >> $GITHUB_STEP_SUMMARY
            echo "- 🔐 **Authentication issues** with JFrog platform" >> $GITHUB_STEP_SUMMARY
            echo "- 🔒 **Insufficient permissions** for admin token" >> $GITHUB_STEP_SUMMARY
            echo "- 🌐 **Network connectivity** problems" >> $GITHUB_STEP_SUMMARY
            echo "- ⚠️ **Resource conflicts** (project/users already exist)" >> $GITHUB_STEP_SUMMARY
            echo "- 🎯 **Missing prerequisites** (GitHub token, environment variables)" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🔧 Recommended actions:" >> $GITHUB_STEP_SUMMARY
            echo "1. 🔍 **Review error logs** for specific failure points" >> $GITHUB_STEP_SUMMARY
            echo "2. 🗑️ **Run Discover Cleanup workflow** to see existing resources" >> $GITHUB_STEP_SUMMARY
            echo "3. 🧹 **Clean up conflicts** before retrying setup" >> $GITHUB_STEP_SUMMARY
            echo "4. ✅ **Verify environment variables** and secrets are configured" >> $GITHUB_STEP_SUMMARY
          fi
